# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup pnpm environment
      run: npm i -g pnpm
           pnpm install
           pnpm add sharp
    - name: Build
      run: pnpm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: page
        folder: dist
    - name: Webhook
      run: curl https://ci.ztsubaki.top/ci?token=123456
